/**
 * Regenerates src/shared/generated-message-keys.ts from the locale dictionaries.
 *
 * The generated file is the single source of truth for MessageKey, so the type
 * system rejects a t('...') call for a key that no longer exists in the
 * dictionaries. Run `npm run i18n` after adding or removing a message.
 *
 * Also verifies that both locales carry exactly the same key set — a key
 * present in one locale but not the other silently falls back to the other
 * language at runtime, which is hard to notice in review.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const localePath = (lang) => resolve(root, 'public/_locales', lang, 'messages.json');
const outputPath = resolve(root, 'src/shared/generated-message-keys.ts');

const read = (lang) => JSON.parse(readFileSync(localePath(lang), 'utf8'));

const ru = read('ru');
const en = read('en');

const ruKeys = Object.keys(ru);
const enKeys = Object.keys(en);

const missingInEn = ruKeys.filter((key) => !(key in en));
const missingInRu = enKeys.filter((key) => !(key in ru));

if (missingInEn.length > 0 || missingInRu.length > 0) {
  if (missingInEn.length > 0) console.error(`Missing in en: ${missingInEn.join(', ')}`);
  if (missingInRu.length > 0) console.error(`Missing in ru: ${missingInRu.join(', ')}`);
  process.exit(1);
}

const empty = ruKeys.filter((key) => !ru[key]?.message || !en[key]?.message);
if (empty.length > 0) {
  console.error(`Empty message for: ${empty.join(', ')}`);
  process.exit(1);
}

const keys = [...ruKeys].sort((a, b) => a.localeCompare(b, 'en'));

const contents = `// Generated by scripts/generate-i18n.mjs. Do not edit manually.
export const messageKeys = [
${keys.map((key) => `  ${JSON.stringify(key)},`).join('\n')}
] as const;

export type MessageKey = (typeof messageKeys)[number];
`;

writeFileSync(outputPath, contents, 'utf8');
console.log(`Wrote ${keys.length} message keys to src/shared/generated-message-keys.ts`);
